In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
from sklearn.naive_bayes import GaussianNB
from sklearn import model_selection
from sklearn.model_selection import train_test_split

### Iris Dataset

In [3]:
iris = sns.load_dataset("iris")

In [4]:
iris.head(7)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa

In [5]:
X = iris.drop("species", axis = 1) 
y = iris["species"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [7]:
gnb = GaussianNB()

In [8]:
gnb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [9]:
y_pred = gnb.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix 
confusion_matrix = confusion_matrix(y_test, y_pred) 
confusion_matrix

array([[15,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]])

In [12]:
from sklearn.metrics import accuracy_score 
print (accuracy_score(y_test, y_pred))

1.0


### Glass Class Type Dataset

In [14]:
glass = pd.read_csv("glassclass.csv")

In [15]:
glass.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [16]:
X = glass.drop("Type", axis =1)
y = glass["Type"]

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

In [18]:
gnb = GaussianNB()

In [30]:
gnb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [32]:
y_pred = gnb.predict(X_test)
y_pred

array([3, 7, 3, 7, 3, 5, 3, 3, 3, 3, 6, 2, 1, 3, 6, 2, 7, 3, 3, 6, 3, 7,
       7, 7, 3, 2, 3, 3, 2, 3, 2, 3, 3, 3, 3, 7, 5, 3, 3, 7, 2, 7, 3, 3,
       1, 6, 2, 3, 2, 3, 3, 3, 3, 3])

In [33]:
from sklearn.metrics import confusion_matrix 
confusion_matrix = confusion_matrix(y_test, y_pred) 
confusion_matrix

array([[ 0,  1, 13,  0,  0,  0],
       [ 1,  4, 13,  1,  1,  1],
       [ 1,  0,  3,  0,  0,  0],
       [ 0,  3,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  0,  8]])

In [22]:
from sklearn.metrics import accuracy_score 
print (accuracy_score(y_test, y_pred))

0.35185185185185186


### Multinomial NB

In [41]:
from sklearn.naive_bayes import MultinomialNB

In [42]:
mnb = MultinomialNB()

In [43]:
mnb.fit(X_train, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [44]:
y_pred = mnb.predict(X_test)

In [45]:
from sklearn.metrics import confusion_matrix 
confusion_matrix = confusion_matrix(y_test, y_pred) 
confusion_matrix

array([[13,  1,  0,  0,  0,  0],
       [13,  8,  0,  0,  0,  0],
       [ 4,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  1,  0,  2],
       [ 0,  1,  0,  0,  0,  2],
       [ 0,  1,  0,  0,  0,  7]])

In [46]:
from sklearn.metrics import accuracy_score 
print (accuracy_score(y_test, y_pred))

0.5370370370370371
