In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('Movie_classification.csv')

In [2]:
df.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  Oscar  
0          223.840  Thriller              23            494       48000      1  
1          243.456     Drama              42            462       43200      0  
2         2022.400    Comedy              38            458       69400      1  
3          225.344     Drama              45            472       66800      1  
4          225.792     Drama              55            395       72400      1

In [3]:
df.describe()

Marketing expense  Production expense  Multiplex coverage  \
count         506.000000          506.000000          506.000000   
mean           92.270471           77.273557            0.445305   
std           172.030902           13.720706            0.115878   
min            20.126400           55.920000            0.129000   
25%            21.640900           65.380000            0.376000   
50%            25.130200           74.380000            0.462000   
75%            93.541650           91.200000            0.551000   
max          1799.524000          110.480000            0.615000   

             Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
count    506.000000    506.000000          506.000000           506.000000   
mean   34911.144022    142.074901            8.014002             8.185613   
std     3903.038232     28.148861            1.054266             1.054290   
min    19781.355000     76.400000            3.840000             4.035000   
25%    32693.952500    118.525000            7.316250             7.503750   
50%    34488.217500    151.000000            8.307500             8.495000   
75%    36793.542500    167.575000            8.865000             9.030000   
max    48772.900000    173.500000            9.435000             9.540000   

       Director_rating  Producer_rating  Critic_rating  Trailer_views  \
count       506.000000       506.000000     506.000000     506.000000   
mean          8.019664         8.190514       7.810870  449860.715415   
std           1.059899         1.049601       0.659699   68917.763145   
min           3.840000         4.030000       6.600000  212912.000000   
25%           7.296250         7.507500       7.200000  409128.000000   
50%           8.312500         8.465000       7.960000  462460.000000   
75%           8.883750         9.030000       8.260000  500247.500000   
max           9.425000         9.635000       9.400000  567784.000000   

       Time_taken  Twitter_hastags  Avg_age_actors  Num_multiplex  \
count  494.000000       506.000000      506.000000     506.000000   
mean   157.391498       260.832095       39.181818     545.043478   
std     31.295161       104.779133       12.513697     106.332889   
min      0.000000       201.152000        3.000000     333.000000   
25%    132.300000       223.796000       28.000000     465.000000   
50%    160.000000       254.400000       39.000000     535.500000   
75%    181.890000       283.416000       50.000000     614.750000   
max    217.520000      2022.400000       60.000000     868.000000   

          Collection       Oscar  
count     506.000000  506.000000  
mean    45057.707510    0.545455  
std     18364.351764    0.498422  
min     10000.000000    0.000000  
25%     34050.000000    0.000000  
50%     42400.000000    1.000000  
75%     50000.000000    1.000000  
max    100000.000000    1.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
Marketing expense      506 non-null float64
Production expense     506 non-null float64
Multiplex coverage     506 non-null float64
Budget                 506 non-null float64
Movie_length           506 non-null float64
Lead_ Actor_Rating     506 non-null float64
Lead_Actress_rating    506 non-null float64
Director_rating        506 non-null float64
Producer_rating        506 non-null float64
Critic_rating          506 non-null float64
Trailer_views          506 non-null int64
3D_available           506 non-null object
Time_taken             494 non-null float64
Twitter_hastags        506 non-null float64
Genre                  506 non-null object
Avg_age_actors         506 non-null int64
Num_multiplex          506 non-null int64
Collection             506 non-null int64
Oscar                  506 non-null int64
dtypes: float64(12), int64(5), object(2)
memory usage: 75.2+ KB


In [5]:
df.Time_taken = df.Time_taken.fillna(df.Time_taken.mean())

In [6]:
df = pd.get_dummies(df, columns = ["3D_available", "Genre"],drop_first = True)
#drop_first will drop the index col

In [7]:
x = df.loc[:, df.columns != "Oscar"]

In [8]:
x.shape

(506, 20)

In [9]:
y = df["Oscar"]

#Using STATSMODEL

In [10]:
import statsmodels.api as sm1

In [11]:
x_cons = sm1.add_constant(x)
x_cons.head()

/Users/rameshveer/Applications/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)


const  Marketing expense  Production expense  Multiplex coverage  \
0    1.0            20.1264               59.62               0.462   
1    1.0            20.5462               69.14               0.531   
2    1.0            20.5458               69.14               0.531   
3    1.0            20.6474               59.36               0.542   
4    1.0            21.3810               59.36               0.542   

      Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0  36524.125         138.7               7.825                8.095   
1  35668.655         152.4               7.505                7.650   
2  39912.675         134.6               7.485                7.570   
3  38873.890         119.3               6.895                7.035   
4  39701.585         127.7               6.920                7.070   

   Director_rating  Producer_rating  ...  Trailer_views  Time_taken  \
0            7.910            7.995  ...         527367      109.60   
1            7.440            7.470  ...         494055      146.64   
2            7.495            7.515  ...         547051      147.88   
3            6.920            7.020  ...         516279      185.36   
4            6.815            7.070  ...         531448      176.48   

   Twitter_hastags  Avg_age_actors  Num_multiplex  Collection  \
0          223.840              23            494       48000   
1          243.456              42            462       43200   
2         2022.400              38            458       69400   
3          225.344              45            472       66800   
4          225.792              55            395       72400   

   3D_available_YES  Genre_Comedy  Genre_Drama  Genre_Thriller  
0                 1             0            0               1  
1                 0             0            1               0  
2                 0             1            0               0  
3                 1             0            1               0  
4                 0             0            1               0  

[5 rows x 21 columns]

In [12]:
import statsmodels.discrete.discrete_model as sm

# logit is a method which uses Max Likelihood method to predict the below summary

In [13]:
logit = sm.Logit(y, x_cons).fit()

Optimization terminated successfully.
         Current function value: 0.581579
         Iterations 7


In [14]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  Oscar   No. Observations:                  506
Model:                          Logit   Df Residuals:                      485
Method:                           MLE   Df Model:                           20
Date:                Sat, 01 Feb 2020   Pseudo R-squ.:                  0.1559
Time:                        11:18:09   Log-Likelihood:                -294.28
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 3.360e-14
=======================================================================================
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
const                  20.9433      4.164      5.030      0.000      12.782      29.104
Marketing expense       0.0007      0.001      1.016      0.310      -0.001       0.002
Production expense      0.0045      0.013      0.353      0.724      -0.021       0.030
Multiplex coverage     -4.9238      2.576     -1.912      0.056      -9.972       0.124
Budget                 -0.0002   4.83e-05     -3.823      0.000      -0.000      -9e-05
Movie_length            0.0058      0.006      0.920      0.358      -0.007       0.018
Lead_ Actor_Rating      2.0478      1.676      1.222      0.222      -1.238       5.333
Lead_Actress_rating    -2.5189      1.794     -1.404      0.160      -6.035       0.998
Director_rating         1.8018      1.744      1.033      0.301      -1.616       5.220
Producer_rating        -2.0443      0.960     -2.130      0.033      -3.926      -0.163
Critic_rating          -0.3868      0.169     -2.289      0.022      -0.718      -0.056
Trailer_views       -1.502e-05   2.99e-06     -5.028      0.000   -2.09e-05   -9.16e-06
Time_taken             -0.0075      0.003     -2.225      0.026      -0.014      -0.001
Twitter_hastags         0.0028      0.002      1.163      0.245      -0.002       0.007
Avg_age_actors          0.0038      0.008      0.467      0.641      -0.012       0.020
Num_multiplex          -0.0025      0.002     -1.057      0.290      -0.007       0.002
Collection              0.0001   1.42e-05      7.340      0.000    7.66e-05       0.000
3D_available_YES        0.2217      0.206      1.075      0.282      -0.182       0.626
Genre_Comedy           -0.0363      0.323     -0.112      0.910      -0.669       0.596
Genre_Drama            -0.0219      0.351     -0.063      0.950      -0.709       0.665
Genre_Thriller         -0.3932      0.315     -1.250      0.211      -1.010       0.223
=======================================================================================
"""

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [17]:
print (x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(404, 20) (102, 20) (404,) (102,)


In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
sc = StandardScaler().fit(x_train)

In [20]:
x_train_std = sc.transform(x_train)

In [21]:
x_test_std = sc.transform(x_test)
x_test_std.shape

(102, 20)

### SVM - Classification :

In [22]:
from sklearn.svm import SVC

In [34]:
from sklearn import svm

In [23]:
svc = SVC(kernel = 'linear', C = 0.01)

In [24]:
svc.fit(x_train_std, y_train)

SVC(C=0.01, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [25]:
y_test_pred = svc.predict(x_test_std)
y_test_pred

array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0])

In [26]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [27]:
confusion_matrix(y_test, y_test_pred)

array([[11, 33],
       [ 5, 53]])

In [28]:
accuracy_score(y_test, y_test_pred)

0.6274509803921569

In [29]:
svc.n_support_

array([186, 189], dtype=int32)

### Hyper Parameter Tuning

In [30]:
from sklearn.model_selection import GridSearchCV

In [31]:
params = {'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50, 100, 500, 1000)}

In [35]:
clf_svm_1 = svm.SVC(kernel = "linear")

### Below parameters are passed in SVM for Hyper Tuning -- expl reqd?

In [37]:
svm_grid_lin = GridSearchCV(clf_svm_1, params, n_jobs = -1, cv = 10, verbose = 1, scoring = 'accuracy')

In [38]:
svm_grid_lin.fit(x_train_std, y_train)

Fitting 10 folds for each of 13 candidates, totalling 130 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done 130 out of 130 | elapsed:  1.4min finished
/Users/rameshveer/Applications/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='linear',
                           max_iter=-1, probability=False, random_state=None,
                           shrinking=True, tol=0.001, verbose=False),
             iid='warn', n_jobs=-1,
             param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50,
                               100, 500, 1000)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=1)

In [39]:
svm_grid_lin.best_params_

{'C': 0.5}

In [40]:
linsvm_clf = svm_grid_lin.best_estimator_

In [42]:
accuracy_score(y_test, linsvm_clf.predict(x_test_std))

0.5980392156862745

### Polynomial Kernel

In [43]:
clf_svm_p3 = svm.SVC(kernel = 'poly', degree = 2, C = 0.1)

In [45]:
clf_svm_p3.fit(x_train_std, y_train)

SVC(C=0.1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=2, gamma='auto_deprecated',
    kernel='poly', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [47]:
y_train_pred = clf_svm_p3.predict(x_train_std)

In [48]:
y_test_pred = clf_svm_p3.predict(x_test_std)

In [49]:
accuracy_score(y_test, y_test_pred)

0.5588235294117647

In [50]:
clf_svm_p3.n_support_

array([185, 194], dtype=int32)

### Radial Kernel

In [51]:
clf_svm_r = svm.SVC(kernel = 'rbf', gamma = 0.5, C = 10)

In [53]:
clf_svm_r.fit(x_train_std, y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.5, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [54]:
y_train_pred = clf_svm_r.predict(x_train_std)

In [55]:
y_test_pred = clf_svm_r.predict(x_test_std)

In [56]:
accuracy_score(y_test, y_test_pred)

0.6176470588235294

In [57]:
clf_svm_r.n_support_

array([186, 218], dtype=int32)

### Radial Grid

In [58]:
params = {'C' :(0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50), 'gamma':(0.001, 0.01, 0.1, 0.5, 1)}

In [59]:
clf_svm_r = svm.SVC(kernel = 'rbf')

In [60]:
svm_grid_rad = GridSearchCV(clf_svm_r, params, n_jobs = -1, cv = 3, verbose = 1, scoring = 'accuracy')

In [61]:
svm_grid_rad.fit(x_train_std, y_train)

Fitting 3 folds for each of 40 candidates, totalling 120 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done 120 out of 120 | elapsed:    3.3s finished
/Users/rameshveer/Applications/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:813: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=3, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=-1,
             param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50),
                         'gamma': (0.001, 0.01, 0.1, 0.5, 1)},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=1)

In [62]:
svm_grid_rad.best_params_

{'C': 50, 'gamma': 0.001}

In [63]:
radsvm_clf = svm_grid_rad.best_estimator_

In [64]:
accuracy_score(y_test, radsvm_clf.predict(x_test_std))

0.6176470588235294

c ?
gamma ?
